"""修改任务模型：移除actual_volume字段，增加status_type字段；为降档和合并记录增加派车单号字段

Revision ID: 2a9f3af6e8a7
Revises: 8cc0ef138595
Create Date: 2025-10-03 10:44:09.116385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a9f3af6e8a7'
down_revision = '8cc0ef138595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manual_dispatch_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_type', sa.Integer(), nullable=True, comment='任务状态类型：0正常/1降档/2合并'))
        batch_op.drop_column('actual_volume')

    with op.batch_alter_table('vehicle_downgrade_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dispatch_number', sa.String(length=100), nullable=True, comment='派车单号'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('vehicle_merge_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_dispatch_number', sa.String(length=100), nullable=True, comment='源派车单号'))
        batch_op.add_column(sa.Column('target_dispatch_number', sa.String(length=100), nullable=True, comment='目标派车单号'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_foreign_key('fk_vehicle_merge_records_operator_id', 'User', ['operator_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_merge_records', schema=None) as batch_op:
        batch_op.drop_constraint('fk_vehicle_merge_records_operator_id', type_='foreignkey')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('target_dispatch_number')
        batch_op.drop_column('source_dispatch_number')

    with op.batch_alter_table('vehicle_downgrade_records', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('dispatch_number')

    with op.batch_alter_table('manual_dispatch_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_volume', sa.INTEGER(), nullable=True))
        batch_op.drop_column('status_type')

    # ### end Alembic commands ###
