"""remove_audit_fields_from_manual_dispatch_tasks

Revision ID: 32e365216ced
Revises: 3a763b09bf46
Create Date: 2025-09-23 16:44:50.499522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32e365216ced'
down_revision = '3a763b09bf46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manual_dispatch_tasks', schema=None) as batch_op:
        batch_op.drop_column('auditor_role')
        batch_op.drop_column('assigned_supplier_id')
        batch_op.drop_column('audit_time')
        batch_op.drop_column('audit_note')
        batch_op.drop_column('auditor_user_id')
        batch_op.drop_column('audit_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manual_dispatch_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audit_status', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('auditor_user_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('audit_note', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('audit_time', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('assigned_supplier_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('auditor_role', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
