"""add required_volume to manual_dispatch_tasks

Revision ID: 36eb3919f90c
Revises: b7acbedfbb9b
Create Date: 2025-09-20 19:19:10.097088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36eb3919f90c'
down_revision = 'b7acbedfbb9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manual_dispatch_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required_volume', sa.Integer(), nullable=True, comment='需求容积'))
        batch_op.drop_column('actual_volume')

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_vehicles_task_id_unique'))
        batch_op.drop_constraint(batch_op.f('uq_vehicles_task_id'), type_='unique')
        batch_op.drop_column('driver_name')
        batch_op.drop_column('driver_id_card')
        batch_op.drop_column('driver_phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_phone', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('driver_id_card', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('driver_name', sa.TEXT(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_vehicles_task_id'), ['task_id'])
        batch_op.create_index(batch_op.f('idx_vehicles_task_id_unique'), ['task_id'], unique=1)

    with op.batch_alter_table('manual_dispatch_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_volume', sa.INTEGER(), nullable=True))
        batch_op.drop_column('required_volume')

    # ### end Alembic commands ###
