"""remove target_task_id and target_vehicle_id from vehicle_merge_records

Revision ID: 3d807e4f0ab0
Revises: 2a9f3af6e8a7
Create Date: 2025-10-04 08:30:56.011365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d807e4f0ab0'
down_revision = '2a9f3af6e8a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_merge_records', schema=None) as batch_op:
        batch_op.drop_column('target_task_id')
        batch_op.drop_column('target_vehicle_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_merge_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_vehicle_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('target_task_id', sa.VARCHAR(length=50), nullable=True))
        batch_op.create_foreign_key(None, 'vehicles', ['target_vehicle_id'], ['id'])
    # ### end Alembic commands ###
