"""add missing manual_dispatch_tasks columns (origin_bureau etc)

Revision ID: 3f5b4f385613
Revises: f2d36e8914d2
Create Date: 2025-09-12 15:32:29.688463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f5b4f385613'
down_revision = 'f2d36e8914d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manual_dispatch_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origin_bureau', sa.String(length=100), nullable=True, comment='始发局'))
        batch_op.add_column(sa.Column('mail_route_name', sa.String(length=100), nullable=True, comment='邮路名称'))
        batch_op.add_column(sa.Column('organizing_unit', sa.String(length=100), nullable=True, comment='组开单位（承运商）'))
        batch_op.add_column(sa.Column('standard_weight', sa.String(length=20), nullable=True, comment='标准吨位'))
        batch_op.add_column(sa.Column('standard_volume', sa.Integer(), nullable=True, comment='标准容积'))
        batch_op.add_column(sa.Column('actual_volume', sa.Integer(), nullable=True, comment='实际需求容积'))
        batch_op.drop_column('carrier_company')
        batch_op.drop_column('weight')
        batch_op.drop_column('start_bureau')
        batch_op.drop_column('volume')
        batch_op.drop_column('route_name')
        batch_op.drop_column('route_direction')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manual_dispatch_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('route_direction', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('route_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('volume', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('start_bureau', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('carrier_company', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('actual_volume')
        batch_op.drop_column('standard_volume')
        batch_op.drop_column('standard_weight')
        batch_op.drop_column('organizing_unit')
        batch_op.drop_column('mail_route_name')
        batch_op.drop_column('origin_bureau')

    # ### end Alembic commands ###
