"""create_file_records_table

Revision ID: 553a2a22756a
Revises: 3d807e4f0ab0
Create Date: 2025-10-05 09:49:45.305385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '553a2a22756a'
down_revision = '3d807e4f0ab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_records',
    sa.Column('id', sa.Integer(), nullable=False, comment='文件记录ID'),
    sa.Column('original_filename', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('stored_filename', sa.String(length=255), nullable=False, comment='存储文件名'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='文件相对路径'),
    sa.Column('file_url', sa.String(length=500), nullable=False, comment='文件访问URL'),
    sa.Column('file_type', sa.String(length=50), nullable=False, comment='文件类型分类'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='文件大小（字节）'),
    sa.Column('mime_type', sa.String(length=100), nullable=True, comment='MIME类型'),
    sa.Column('business_type', sa.String(length=50), nullable=True, comment='业务类型'),
    sa.Column('business_id', sa.String(length=100), nullable=True, comment='业务ID'),
    sa.Column('uploaded_by', sa.Integer(), nullable=True, comment='上传人ID'),
    sa.Column('upload_time', sa.DateTime(), nullable=True, comment='上传时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否已删除'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_file_records_business', 'file_records', ['business_type', 'business_id'], unique=False)
    op.create_index('idx_file_records_type', 'file_records', ['file_type'], unique=False)
    op.create_index('idx_file_records_uploader', 'file_records', ['uploaded_by'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_file_records_uploader', table_name='file_records')
    op.drop_index('idx_file_records_type', table_name='file_records')
    op.drop_index('idx_file_records_business', table_name='file_records')
    op.drop_table('file_records')
    # ### end Alembic commands ###
