"""add_appeal_review_fields_to_manual_dispatch_tasks

Revision ID: 70e1f79df5cf
Revises: aae937d6b897
Create Date: 2025-10-07 10:50:15.549056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70e1f79df5cf'
down_revision = 'aae937d6b897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_records', schema=None) as batch_op:
        batch_op.create_index('idx_file_records_upload_time', ['upload_time'], unique=False)

    with op.batch_alter_table('manual_dispatch_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appeal_reviewed_by', sa.Integer(), nullable=True, comment='申诉审核人用户ID'))
        batch_op.add_column(sa.Column('appeal_reviewed_at', sa.String(length=20), nullable=True, comment='申诉审核时间'))
        batch_op.add_column(sa.Column('appeal_review_result', sa.String(length=20), nullable=True, comment='申诉审核结果：approved/rejected'))
        batch_op.add_column(sa.Column('appeal_review_notes', sa.Text(), nullable=True, comment='申诉审核备注'))
        batch_op.add_column(sa.Column('final_confirmed_tonnage', sa.String(length=20), nullable=True, comment='最终确认吨位'))
        batch_op.add_column(sa.Column('completed_at', sa.String(length=20), nullable=True, comment='任务完成时间'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manual_dispatch_tasks', schema=None) as batch_op:
        batch_op.drop_column('completed_at')
        batch_op.drop_column('final_confirmed_tonnage')
        batch_op.drop_column('appeal_review_notes')
        batch_op.drop_column('appeal_review_result')
        batch_op.drop_column('appeal_reviewed_at')
        batch_op.drop_column('appeal_reviewed_by')

    with op.batch_alter_table('file_records', schema=None) as batch_op:
        batch_op.drop_index('idx_file_records_upload_time')

    # ### end Alembic commands ###
