"""Add actual_volume, required_weight and actual_weight to manual_dispatch_tasks

Revision ID: a8d661858f9f
Revises: 36eb3919f90c
Create Date: 2025-09-20 19:39:31.349677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8d661858f9f'
down_revision = '36eb3919f90c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manual_dispatch_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required_weight', sa.String(length=20), nullable=True, comment='需求吨位'))
        batch_op.add_column(sa.Column('actual_weight', sa.String(length=20), nullable=True, comment='实际吨位'))
        batch_op.add_column(sa.Column('actual_volume', sa.Integer(), nullable=True, comment='实际容积'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manual_dispatch_tasks', schema=None) as batch_op:
        batch_op.drop_column('actual_volume')
        batch_op.drop_column('actual_weight')
        batch_op.drop_column('required_weight')

    # ### end Alembic commands ###
