"""Add task vehicle unique constraint

Revision ID: add_task_vehicle_unique_constraint
Revises: add_vehicle_task_id_constraint
Create Date: 2024-01-15 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_task_vehicle_unique_constraint'
down_revision = 'add_vehicle_task_id_constraint'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 添加唯一约束：一个任务只能关联一辆车辆
    # 这个约束确保 task_id 在 vehicles 表中是唯一的
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_unique_constraint(
            'uq_vehicles_task_id', 
            ['task_id']
        )
    
    # 为提高查询性能，添加相关索引
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        # 如果索引不存在，则创建
        batch_op.create_index(
            'idx_vehicles_task_id_unique', 
            ['task_id'], 
            unique=True
        )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 移除唯一约束和索引
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_constraint('uq_vehicles_task_id', type_='unique')
        batch_op.drop_index('idx_vehicles_task_id_unique')
    
    # ### end Alembic commands ###