"""Add vehicle capacity reference fields and vehicle task_id constraint

Revision ID: add_vehicle_capacity_reference_fields
Revises: 
Create Date: 2024-01-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_vehicle_capacity_reference_fields'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. 为 vehicle_capacity_reference 表添加新字段
    with op.batch_alter_table('vehicle_capacity_reference', schema=None) as batch_op:
        batch_op.add_column(sa.Column('carriage_number', sa.String(length=50), nullable=True, comment='车厢号'))
        batch_op.add_column(sa.Column('vehicle_category', sa.String(length=10), nullable=True, comment='车辆分类：单车/挂车'))
        batch_op.add_column(sa.Column('frequent_companies', sa.Text(), nullable=True, comment='常用公司列表，JSON格式'))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True, comment='状态：active/inactive'))
        batch_op.add_column(sa.Column('original_capacity', sa.Float(), nullable=True, comment='原始载重量(吨)'))
    
    # 2. 更新 vehicle_capacity_reference 表的默认值
    op.execute("UPDATE vehicle_capacity_reference SET frequent_companies = '[]' WHERE frequent_companies IS NULL")
    op.execute("UPDATE vehicle_capacity_reference SET status = 'active' WHERE status IS NULL")
    
    # 3. 为 vehicles 表的 task_id 字段添加非空约束（在数据迁移后执行）
    # 注意：这个操作应该在数据迁移脚本执行后再运行
    # with op.batch_alter_table('vehicles', schema=None) as batch_op:
    #     batch_op.alter_column('task_id', nullable=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. 移除 vehicles 表的 task_id 非空约束
    # with op.batch_alter_table('vehicles', schema=None) as batch_op:
    #     batch_op.alter_column('task_id', nullable=True)
    
    # 2. 移除 vehicle_capacity_reference 表的新字段
    with op.batch_alter_table('vehicle_capacity_reference', schema=None) as batch_op:
        batch_op.drop_column('original_capacity')
        batch_op.drop_column('status')
        batch_op.drop_column('frequent_companies')
        batch_op.drop_column('vehicle_category')
        batch_op.drop_column('carriage_number')
    
    # ### end Alembic commands ###