"""Add organizing_unit_id to manual_dispatch_tasks

Revision ID: add_organizing_unit_id
Revises: 
Create Date: 2024-01-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_organizing_unit_id'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manual_dispatch_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organizing_unit_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_manual_dispatch_tasks_organizing_unit_id', 'dispatch_units', ['organizing_unit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manual_dispatch_tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_manual_dispatch_tasks_organizing_unit_id', type_='foreignkey')
        batch_op.drop_column('organizing_unit_id')
    # ### end Alembic commands ###