"""Add vehicle task_id not null constraint

Revision ID: add_vehicle_task_id_constraint
Revises: add_vehicle_capacity_reference_fields
Create Date: 2024-01-15 11:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_vehicle_task_id_constraint'
down_revision = 'add_vehicle_capacity_reference_fields'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 在执行此迁移前，请确保已经运行了数据迁移脚本
    # python scripts/migrate_vehicle_data.py --migrate
    # python scripts/migrate_vehicle_data.py --cleanup
    
    # 为 vehicles 表的 task_id 字段添加非空约束
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.alter_column('task_id', 
                            existing_type=sa.String(length=50),
                            nullable=False,
                            comment='关联任务ID')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 移除 vehicles 表的 task_id 非空约束
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.alter_column('task_id',
                            existing_type=sa.String(length=50),
                            nullable=True,
                            comment='关联任务ID')
    
    # ### end Alembic commands ###