"""Add next_handler_role and next_handler_user_id to dispatch_status_history

Revision ID: add_next_handler_role
Revises: a8d661858f9f
Create Date: 2025-09-21 20:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_next_handler_role'
down_revision = 'a8d661858f9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispatch_status_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_handler_role', sa.String(length=50), nullable=True, comment='下一阶段操作人角色'))
        batch_op.add_column(sa.Column('next_handler_user_id', sa.Integer(), nullable=True, comment='下一阶段操作人ID'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispatch_status_history', schema=None) as batch_op:
        batch_op.drop_column('next_handler_user_id')
        batch_op.drop_column('next_handler_role')

    # ### end Alembic commands ###