"""Add business_type field to manual_dispatch_tasks

Revision ID: ca6e10835313
Revises: 3f5b4f385613
Create Date: 2025-09-13 17:34:04.901628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca6e10835313'
down_revision = '3f5b4f385613'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manual_dispatch_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_type', sa.String(length=20), nullable=True, comment='业务类型：自办派车/委办派车'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manual_dispatch_tasks', schema=None) as batch_op:
        batch_op.drop_column('business_type')

    # ### end Alembic commands ###
