"""Remove standard_weight and standard_volume fields from manual_dispatch_tasks

Revision ID: e99179c55348
Revises: a8d661858f9f
Create Date: 2025-09-20 19:47:54.545538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e99179c55348'
down_revision = 'a8d661858f9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manual_dispatch_tasks', schema=None) as batch_op:
        batch_op.drop_column('standard_volume')
        batch_op.drop_column('standard_weight')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manual_dispatch_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('standard_weight', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('standard_volume', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
