"""Initial migration

Revision ID: f2d36e8914d2
Revises: 
Create Date: 2025-09-08 13:45:01.808549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2d36e8914d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Permission', schema=None) as batch_op:
        batch_op.drop_index('idx_permission_module')
        batch_op.drop_index('idx_permission_name')

    op.drop_table('Permission')
    op.drop_table('modules')
    with op.batch_alter_table('RolePermission', schema=None) as batch_op:
        batch_op.drop_index('idx_role_permission_permission_id')
        batch_op.drop_index('idx_role_permission_role_id')

    op.drop_table('RolePermission')
    with op.batch_alter_table('Company', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('bank_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('account_number',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('contact_person',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('contact_phone',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('Role', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index('idx_role_name')

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.alter_column('full_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index('idx_user_company_id')
        batch_op.drop_index('idx_user_email')
        batch_op.drop_index('idx_user_username')

    with op.batch_alter_table('UserRole', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'))
        batch_op.drop_index('idx_user_role_role_id')
        batch_op.drop_index('idx_user_role_user_id')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'User', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'Role', ['role_id'], ['id'])

    with op.batch_alter_table('dispatch_status_history', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('task_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('status_change',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('operator',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index('idx_history_task')
        batch_op.drop_index('idx_history_task_id')
        batch_op.drop_index('idx_history_timestamp')
        batch_op.drop_index('idx_timestamp')

    with op.batch_alter_table('manual_dispatch_tasks', schema=None) as batch_op:
        batch_op.alter_column('task_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('required_date',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.alter_column('start_bureau',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('route_direction',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('carrier_company',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('route_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('transport_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('requirement_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('volume',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('weight',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=True,
               existing_server_default=sa.text("'待提交'"))
        batch_op.alter_column('dispatch_track',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               nullable=True,
               existing_server_default=sa.text("'轨道A'"))
        batch_op.alter_column('initiator_role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=True,
               existing_server_default=sa.text("'车间地调'"))
        batch_op.alter_column('initiator_user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('initiator_department',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('auditor_role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('audit_status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'待审核'"))
        batch_op.alter_column('audit_time',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('current_handler_role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index('idx_assigned_supplier_id')
        batch_op.drop_index('idx_auditor_user_id')
        batch_op.drop_index('idx_carrier_company')
        batch_op.drop_index('idx_current_handler_user_id')
        batch_op.drop_index('idx_dispatch_track')
        batch_op.drop_index('idx_initiator_user_id')
        batch_op.drop_index('idx_manual_dispatch_auditor')
        batch_op.drop_index('idx_manual_dispatch_date')
        batch_op.drop_index('idx_manual_dispatch_handler')
        batch_op.drop_index('idx_manual_dispatch_initiator')
        batch_op.drop_index('idx_manual_dispatch_status')
        batch_op.drop_index('idx_manual_dispatch_supplier')
        batch_op.drop_index('idx_manual_dispatch_track')
        batch_op.drop_index('idx_required_date')
        batch_op.drop_index('idx_status')
        batch_op.drop_index('idx_task_id')
        batch_op.drop_index('idx_tasks_auditor')
        batch_op.drop_index('idx_tasks_date')
        batch_op.drop_index('idx_tasks_handler')
        batch_op.drop_index('idx_tasks_initiator')
        batch_op.drop_index('idx_tasks_initiator_status')
        batch_op.drop_index('idx_tasks_required_date')
        batch_op.drop_index('idx_tasks_status')
        batch_op.drop_index('idx_tasks_status_date')
        batch_op.drop_index('idx_tasks_track')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('vehicle_capacity_reference', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('vehicle_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.alter_column('standard_volume',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=True)
        batch_op.alter_column('license_plate',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index('idx_capacity_license_plate')
        batch_op.drop_index('idx_capacity_vehicle_type')
        batch_op.drop_index('idx_vehicle_capacity_license_plate')
        batch_op.drop_index('idx_vehicle_capacity_type')
        batch_op.drop_index('idx_vehicle_type')

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('task_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('manifest_number',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('dispatch_number',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('license_plate',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.alter_column('carriage_number',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('actual_volume',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('volume_photo_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('required_volume',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('confirmed_volume',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_index('idx_license_plate')
        batch_op.drop_index('idx_unique_dispatch')
        batch_op.drop_index('idx_unique_manifest')
        batch_op.drop_index('idx_vehicles_license_plate')
        batch_op.drop_index('idx_vehicles_manifest_number')
        batch_op.drop_index('idx_vehicles_task')
        batch_op.drop_index('idx_vehicles_task_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index('idx_vehicles_task_id', ['task_id'], unique=False)
        batch_op.create_index('idx_vehicles_task', ['task_id'], unique=False)
        batch_op.create_index('idx_vehicles_manifest_number', ['manifest_number'], unique=False)
        batch_op.create_index('idx_vehicles_license_plate', ['license_plate'], unique=False)
        batch_op.create_index('idx_unique_manifest', ['manifest_number'], unique=1)
        batch_op.create_index('idx_unique_dispatch', ['dispatch_number'], unique=1)
        batch_op.create_index('idx_license_plate', ['license_plate'], unique=False)
        batch_op.alter_column('confirmed_volume',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('required_volume',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('volume_photo_url',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('actual_volume',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('carriage_number',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('license_plate',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('dispatch_number',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('manifest_number',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('task_id',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('vehicle_capacity_reference', schema=None) as batch_op:
        batch_op.create_index('idx_vehicle_type', ['vehicle_type'], unique=False)
        batch_op.create_index('idx_vehicle_capacity_type', ['vehicle_type'], unique=False)
        batch_op.create_index('idx_vehicle_capacity_license_plate', ['license_plate'], unique=False)
        batch_op.create_index('idx_capacity_vehicle_type', ['vehicle_type'], unique=False)
        batch_op.create_index('idx_capacity_license_plate', ['license_plate'], unique=1)
        batch_op.alter_column('updated_at',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('license_plate',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('standard_volume',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=False)
        batch_op.alter_column('vehicle_type',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('manual_dispatch_tasks', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'Company', ['carrier_company'], ['name'])
        batch_op.create_index('idx_tasks_track', ['dispatch_track'], unique=False)
        batch_op.create_index('idx_tasks_status_date', ['status', 'required_date'], unique=False)
        batch_op.create_index('idx_tasks_status', ['status'], unique=False)
        batch_op.create_index('idx_tasks_required_date', ['required_date'], unique=False)
        batch_op.create_index('idx_tasks_initiator_status', ['initiator_user_id', 'status'], unique=False)
        batch_op.create_index('idx_tasks_initiator', ['initiator_user_id'], unique=False)
        batch_op.create_index('idx_tasks_handler', ['current_handler_user_id'], unique=False)
        batch_op.create_index('idx_tasks_date', ['required_date'], unique=False)
        batch_op.create_index('idx_tasks_auditor', ['auditor_user_id'], unique=False)
        batch_op.create_index('idx_task_id', ['task_id'], unique=False)
        batch_op.create_index('idx_status', ['status'], unique=False)
        batch_op.create_index('idx_required_date', ['required_date'], unique=False)
        batch_op.create_index('idx_manual_dispatch_track', ['dispatch_track'], unique=False)
        batch_op.create_index('idx_manual_dispatch_supplier', ['assigned_supplier_id'], unique=False)
        batch_op.create_index('idx_manual_dispatch_status', ['status'], unique=False)
        batch_op.create_index('idx_manual_dispatch_initiator', ['initiator_user_id'], unique=False)
        batch_op.create_index('idx_manual_dispatch_handler', ['current_handler_user_id'], unique=False)
        batch_op.create_index('idx_manual_dispatch_date', ['required_date'], unique=False)
        batch_op.create_index('idx_manual_dispatch_auditor', ['auditor_user_id'], unique=False)
        batch_op.create_index('idx_initiator_user_id', ['initiator_user_id'], unique=False)
        batch_op.create_index('idx_dispatch_track', ['dispatch_track'], unique=False)
        batch_op.create_index('idx_current_handler_user_id', ['current_handler_user_id'], unique=False)
        batch_op.create_index('idx_carrier_company', ['carrier_company'], unique=False)
        batch_op.create_index('idx_auditor_user_id', ['auditor_user_id'], unique=False)
        batch_op.create_index('idx_assigned_supplier_id', ['assigned_supplier_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('current_handler_role',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('audit_time',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('audit_status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'待审核'"))
        batch_op.alter_column('auditor_role',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('initiator_department',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('initiator_user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('initiator_role',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'车间地调'"))
        batch_op.alter_column('dispatch_track',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'轨道A'"))
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'待提交'"))
        batch_op.alter_column('weight',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=False)
        batch_op.alter_column('volume',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('requirement_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('transport_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('route_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('carrier_company',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('route_direction',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('start_bureau',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('required_date',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('task_id',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('dispatch_status_history', schema=None) as batch_op:
        batch_op.create_index('idx_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('idx_history_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('idx_history_task_id', ['task_id'], unique=False)
        batch_op.create_index('idx_history_task', ['task_id'], unique=False)
        batch_op.alter_column('timestamp',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('operator',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('status_change',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('task_id',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('UserRole', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'Role', ['role_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'User', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('idx_user_role_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_user_role_role_id', ['role_id'], unique=False)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.create_index('idx_user_username', ['username'], unique=False)
        batch_op.create_index('idx_user_email', ['email'], unique=1)
        batch_op.create_index('idx_user_company_id', ['company_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('phone',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('full_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=80),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('Role', schema=None) as batch_op:
        batch_op.create_index('idx_role_name', ['name'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('name',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('Company', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('contact_phone',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('contact_person',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('account_number',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('bank_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.create_table('RolePermission',
    sa.Column('role_id', sa.INTEGER(), nullable=False),
    sa.Column('permission_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['Permission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['Role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    with op.batch_alter_table('RolePermission', schema=None) as batch_op:
        batch_op.create_index('idx_role_permission_role_id', ['role_id'], unique=False)
        batch_op.create_index('idx_role_permission_permission_id', ['permission_id'], unique=False)

    op.create_table('modules',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('display_name', sa.TEXT(), nullable=False),
    sa.Column('route_name', sa.TEXT(), nullable=True),
    sa.Column('icon_class', sa.TEXT(), nullable=True),
    sa.Column('sort_order', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.Column('parent_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['modules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Permission',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('module', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('Permission', schema=None) as batch_op:
        batch_op.create_index('idx_permission_name', ['name'], unique=1)
        batch_op.create_index('idx_permission_module', ['module'], unique=False)

    # ### end Alembic commands ###
