"""Update business_type field to support new business type options

Revision ID: updated_business_type_field
Revises: ca6e10835313
Create Date: 2025-09-24 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'updated_business_type_field'
down_revision = 'ca6e10835313'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manual_dispatch_tasks', schema=None) as batch_op:
        batch_op.alter_column('business_type',
               existing_type=sa.String(length=20),
               type_=sa.String(length=20),
               existing_nullable=True,
               comment='业务类型：自办派车/委办派车/大容积派车')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manual_dispatch_tasks', schema=None) as batch_op:
        batch_op.alter_column('business_type',
               existing_type=sa.String(length=20),
               type_=sa.String(length=20),
               existing_nullable=True,
               comment='业务类型：自办派车/委办派车')

    # ### end Alembic commands ###